### ISSUE TITLE
Support for scheduled flink batch jobs

### ISSUE THREAD

**Issue by krishnaarava** [GoogleCloudPlatform/flink-on-k8s-operator#134]
My proposal is to add support for Cron based scheduling in Flink Operator. The CR would need to add new construct lets say "schedule" which would define when it needs to run.

**Comment by functicons** [comment]
Thanks for the proposal, but I'm hesitating to add Cron based scheduling, because it is not a core functionality which has to be built-into the operator. We can easily compose Kubernetes [CronJob](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/) with the operator to achieve the desired functionality.

**Comment by snupy** [comment]
> We can easily compose Kubernetes [CronJob](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/) with the operator to achieve it.

@functicons , do you mean just to fork the operator and add this functionality, or there is another approach?
