### ISSUE TITLE
Double jobs running after killing the job pod

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#147]
When I start a job cluster as per-job mode, I kill the job pod and then I see two running jobs in flink UI .
As I know when kill the job , It will cacelling,and then submit job . but when kill job Pod ,It seem error.

I guess , that kill job pod , It restart the job pod by job replicas. not controller by operator?

**Comment by Mrart** [comment]
@functicons  I suggest use detach mode in flink cmd

**Comment by Mrart** [comment]
@functicons  I think I failed to handle this issue. because when I change to dettach mode ,It will kill all cluster. Do you have any other idea?

**Comment by Mrart** [comment]
@functicons ，about this issue， Do you have any idea？ I am not sure how to reslove it

**Comment by Mrart** [comment]
@hongyegong Do you have any suggest about this issue？

**Comment by hongyegong** [comment]
Can you provide error msg/log?

Also what is per-job mode in your original reference?

**Comment by Mrart** [comment]
ok, I show you how  to get this function.1. start a per-job cluster. 2.kill the job pod. and then you can see the two running jobs in flink ui.

**Comment by Mrart** [comment]
@hongyegong  I think it is a very importent bug in our project. It will make use data run error when two same job running in the cluster.

**Comment by Mrart** [comment]
@functicons , This is very import for our product env, because when we run the jobs double，the streaming data will error. Can you help me！

**Comment by functicons** [comment]
@Mrart okay, I'll look into it.

**Comment by functicons** [comment]
@Mrart IIUC, when killing the job pod, the job automatically recreated one, but it lost the track about the running job in Flink, and resubmited the job which caused the double jobs problem.

Here is my ideas about the solution: 1) change how we submit jobs, now we are using `/opt/flink/bin/flink run ...` to submit jobs, see https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/08394361496e390db35fc770b50d12a16ff592dc/controllers/flinkcluster_converter.go#L580, we need to replace it with a script like `/flink-operator/submit-job.sh ...`; 2) in the `submit-job.sh` we add the logic of checking whether there are running jobs already, if so, simply wait for it to finish instead of submitting a new one; 3) `submit-job.sh` could be generated by the operator and mounted into the job container with ConfigMap.

What do you think?

**Comment by Mrart** [comment]
@functicons  thanks for your ideas. I think change the '/opt/flink/bin/flink run <args>' is a very good idea.
I will running the operator in product env last week. Can you help me fixed the bug before it? I will push our other issue when we fixed.

**Comment by functicons** [comment]
@Mrart Okay, I'll be working on the fix.

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/182

**Comment by functicons** [comment]
@Mrart could you verify the fix #182 ?

**Comment by Mrart** [comment]
@functicons  Thank you very much. I will test It. I am very glad to hear it.
