### ISSUE TITLE
controller-gen@v0.2.0-beta.2 is not support ‘maxDescLen=0’， How to update it?

### ISSUE THREAD

**Issue by Mrart** [GoogleCloudPlatform/flink-on-k8s-operator#242]
when I update to controller-gen@v0.2.4, It need go 1.13.So how to update it?

**Comment by elanv** [comment]
I've created a branch to bump up the k8s lib version to 1.18.
https://github.com/elanv/flink-on-k8s-operator/tree/feature/bump-up

I  tested it with k8s 1.15 and 1.18.
There was no problem, and it seems resolve #210 also.
But I didn't make it PR because It may affet the CI and I didn't test it much.

**Comment by Mrart** [comment]
@elanv  can you push it to master branch，and I will help you test，and push my reviews

**Comment by elanv** [comment]
I concern the PR affects CI.
@functicons @hongyegong What do you think about go.mod update above?

**Comment by functicons** [comment]
@elanv Go ahead pushing a PR, I'll test for it.

**Comment by functicons** [comment]
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/247
