### ISSUE TITLE
Operator does not resubmit failed jobs.

### ISSUE THREAD

**Issue by singalravi** [GoogleCloudPlatform/flink-on-k8s-operator#294]
If a job fails for some reason, operator does not resubmit it. k8s job check the status of the job and exit with error code 1.
```
Checking existing jobs...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar) to method sun.security.krb5.Config.getInstance()
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Waiting for response...
No running jobs.
No scheduled jobs.
---------------------- Terminated Jobs -----------------------
29.07.2020 11:10:48 : 4d3fcf0124ca60eaf0a2a9a9587da802 : SpanNormalizerJob (FAILED)
--------------------------------------------------------------
29.07.2020 11:10:48 : 4d3fcf0124ca60eaf0a2a9a9587da802 : SpanNormalizerJob (FAILED)
Found an existing job, skip resubmitting...

Waiting for job to finish...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-7.0.jar) to method sun.security.krb5.Config.getInstance()
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Waiting for response...
No running jobs.
No scheduled jobs.
---------------------- Terminated Jobs -----------------------
29.07.2020 11:10:48 : 4d3fcf0124ca60eaf0a2a9a9587da802 : SpanNormalizerJob (FAILED)
--------------------------------------------------------------
29.07.2020 11:10:48 : 4d3fcf0124ca60eaf0a2a9a9587da802 : SpanNormalizerJob (FAILED)

Job failed, exiting 1
```
Remove `FAILED` status from `check_existing_jobs()` in `submit-job.sh` script.
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/controllers/flinkcluster_submit_job_script.go#L52

**Comment by functicons** [comment]
This seems to be bug, but I wanted to confirm that you have set `restartPolicy` to `FromSavepointOnFailure`, right?

**Comment by singalravi** [comment]
> This seems to be bug, but I wanted to confirm that you have set `restartPolicy` to `FromSavepointOnFailure`, right?

Yes, the restart policy is set to `FromSavepointOnFailure`.

**Comment by Mrart** [comment]
@functicons  we submit job as dettach mode, as job pod killed ,and other pods is running, the task will failed. becuase we set "
	// Disable the retry mechanism of k8s Job, all retires should be initiated
	// by the operator based on the job restart policy. This is because Flink
	// jobs are stateful, if a job fails after running for 10 hours, we probably
	// don't want to start over from the beginning, instead we want to resume
	// the job from the latest savepoint which means strictly speaking it is no
	// longer the same job as the previous one because the `--fromSavepoint`
	// parameter has changed.
	var backoffLimit int32 = 0
"

**Comment by Mrart** [comment]
@functicons , I have try to fixed this bug. But I have some confusion. 
First: 
   I have try to set backofflimit = 32, I kill the job pods ,the pods will restart. But I cancelled the job ,the job pods will started without checkpoint.  (I don't set fromSavepoint), I think I don't need every job to set savepoint, I need start from the checkpoint(checkpoint path can get for http client).

Second：
  As @singalravi  dscript

@functicons  Can you help me？

**Comment by guruprasathT** [comment]
Facing the same trouble on auto-restart from the **FromSavepointOnFailure**  _Found an existing job, skip resubmitting..._

```
Checking existing jobs...
Waiting for response...
No running jobs.
No scheduled jobs.
---------------------- Terminated Jobs -----------------------
10.09.2020 19:09:16 : 10ec916b024efbe2c75185d35811077c : xts-beta (CANCELED)
--------------------------------------------------------------
10.09.2020 19:09:16 : 10ec916b024efbe2c75185d35811077c : xts-beta (CANCELED)
Found an existing job, skip resubmitting...

Waiting for job to finish...
Waiting for response...
No running jobs.
No scheduled jobs.
---------------------- Terminated Jobs -----------------------
10.09.2020 19:09:16 : 10ec916b024efbe2c75185d35811077c : xts-beta (CANCELED)
--------------------------------------------------------------
```

AYMK, previously `cancelled job` info still exists in the job manager flink api client return the jobList with all the status fails the condition to resubmit the job.

https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/controllers/flinkcluster_submit_job_script.go#L101-L106

Temporarily i have to delete the jobmanager pod and to restart from `FromSavepointOnFailure`.
Any specific reason for the condition to check for all status of the job? (Or will be nice to exclude jobs with status=CANCELED, FAILED?)

with default `backofflimit` and continuos restart causing `flink-operator-controller-manager` pod OOM when multiple jobs facing this trouble.

kindly suggest !

**Comment by guruprasathT** [comment]
For temporary workaround added `jobstore.expiration-time` in the flinkProperties.

**Comment by syucream** [comment]
I faced the same issue. In my case, the k8s job continuously failed with the message `Found an existing job, skip resubmitting...` until the existing job was expired by `jobstore.expiration-time`.

> Or will be nice to exclude jobs with status=CANCELED, FAILED?

I agree, I think the current `check_existing_jobs()` is better to ignore `CANCELED` and `FAILED` if any reason. What do you think about this?

**Comment by functicons** [comment]
The assumption in the current job submission script is that there is at most 1 job in JM, which is now causing the problem of resubmitting failed jobs. If we want to ignore `CANCELED` and `FAILED` states in `check_existing_jobs()`, there could be multiple jobs returned by listing jobs, then we need a way to distinguish which one is the current one. If we find a solution, it is doable.

Another way to fix this problem is to delete and recreate JM, then resubmit the failed job. This will keep the assumption of at most 1 job.

**Comment by witzatom** [comment]
Maybe I'm wrong but this does seem pretty much out of scope for the operator. If you want to keep a job alive, you should use a restart policy. The operator is there mainly for cases where for example a whole node dies and the job cluster has to be spinned up again. I suppose the operator can be a fallback for the restart policy, in some wierd edge cases it might help, but there I think the workaround of `jobstore.expiration-time` seems to work to me. just fine.

**Comment by scathatheworm** [comment]
I've been testing this by manually deleting the job pod to test different failure scenarios, and I run into the flink job being CANCELED by the operator and the the job pod restarted by the operator, which then goes into a loop because it finds a CANCELED job present, errors, and is restarted over and over by the operator.

I would have expected:

1. the flink job doesn't get cancelled because the job pod is killed (I did a kubectl delete, but what happens in case the pod is evicted, for example?)
2. If the job fails or is cancelled, that it is restarted by the job pod and resubmitted.

**Comment by elanv** [comment]
@functicons We determine the status of the Flink job via `wait_for_job` loop in the job submitter.
However, we call Flink REST API in each reconcile loop to get Flink job ID.
What do you think about changing the job submitter to be completed after job submit command executed and determine the Flink job status in reconcile loop with observed Flink job status via REST API, instead of `wait_for_job` loop?

**Comment by elanv** [comment]
I think there is room for improvement in two things with regard to job status tracking.

1. Tracking job status by extracting Job ID when submitting a job. Necessary for job recovery.
2. Tracking job status in operator instead of job submitter. For more reliable monitoring and resource saving.

The first comment I wrote above relates to the second one.

Regarding the first, it looks like the job ID could be extracted from the job submit output. However, since the Flink operator also manages Flink jobs with job ID, it is necessary to ensure that operator and job submitter have the same job ID. There are two possible ways for the flink operator to get the job ID inside the job submitter pod. One is to get the output from executing a command inside the job pod via client-go exec API, and the other is to make a simple web server that provides the job ID and include it in the sidecar container of the job pod. I think it would be sufficient to use client-go exec API. If there are better ways, it would be nice to share it.

**Comment by functicons** [comment]
Finishing the job submitter pod after submitting the the job sounds like a good solution to the problem. But getting job ID from job submitter Pod doesn't seem to be very reliable, because Pods can be deleted or restarted for many reasons. Here is what I am thinking about the implementation:

1) the operator creates the job submitter pod which runs the script to submit the job;
2) after submitting the job, the job submitter keeps running the wait loop until the operator actively deletes the pod.
3) the operator gets job ID(s) from the Flink REST API, and record it in the CR status. It records all job IDs, so it knows which job IDs are old, which is the current. It should guarantee at most 1 running job.
4) let the operator monitors the job status, once the job is running, deletes the job submitter Pod.

**Comment by elanv** [comment]
Your solution looks good to me.
After that, I thought about it a little more, and I thought it would be better if we could directly control the job ID.
So investigated whether there is any way to provide job ID when submit a job,
and I found it is possible via REST API like this:
```bash
# Upload jar
curl -X POST -H "Expect:" -F "jarfile=@examples/streaming/StateMachineExample.jar" http://localhost:28081/jars/upload
{"filename":"/tmp/flink-web-9eaa4829-85ed-478e-b9ac-46df7e1929c8/flink-web-upload/b8303516-6377-4f8c-acf1-60539192b50c_StateMachineExample.jar","status":"success"}

# Run job
curl -d '{"jobId":"abcd014d4c864993a2e5a9287b4a9c5d"}' \
       -H "Content-Type: application/json" \
       -X POST http://localhost:28081/jars/b8303516-6377-4f8c-acf1-60539192b50c_StateMachineExample.jar/run
```

The advantages of this approach are:
- Flink operator can control the job ID by generating the ID and provide it to job.
- We can make the flink job pod lighter as we can use the image that contains only curl.
- When using flink CLI, the job plan is created in the place where the CLI is executed, but when the job is executed after jar upload, the job plan is created in the job manager, so the resource to be occupied by the job pod become very small.

**Comment by functicons** [comment]
Good to know it allows client specified job ID. You ideas look good to me. Would you be able to make this change?

**Comment by elanv** [comment]
Ok, I would like to try it.

**Comment by elanv** [comment]
@functicons What do you think about making job submitter a go program instead of a shell script? Most of the job submitter scripts are being rewritten, but the functional limitations or readability of the shell script are unfortunate.

**Comment by functicons** [comment]
This problem should have been fixed by https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/379
